---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-ui
  namespace: sample-apps
spec:
  selector:
    matchLabels:
      app: apps-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: apps-ui
    spec:
      containers:
        - name: ui
          image: ren1007/todo-apps-ui:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.4"
            requests:
              memory: "256Mi"
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: apps-ui-svc
  namespace: sample-apps
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.10.72
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: apps-ui
